### ISSUE TITLE
Add telemetry in the extension

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/podman-desktop-sandbox-ext#51]
We need to be able to track:
- Installation (see [#3664](https://github.com/containers/podman-desktop/pull/3664))
- Un-installation (see [#3541](https://github.com/containers/podman-desktop/pull/3541))
- errors in installation (see [#3664](https://github.com/containers/podman-desktop/pull/3664))
- Click on "Create New" from the resources page (see [#3697](https://github.com/containers/podman-desktop/pull/3697))
- Click on "create" in the Create a Developer Sandbox  (see  [#3634](https://github.com/containers/podman-desktop/pull/3534))
- Click on "Close/Cancel" in the Create a Developer Sandbox (see [#3698](https://github.com/containers/podman-desktop/pull/3698))
- Click on "Log into Developer Sandbox" button (see [#91](https://github.com/redhat-developer/podman-desktop-sandbox-ext/pull/91))
- Click on "Delete" the resource (is tracked already as 'deleteProviderConnection' event [here](https://github.com/containers/podman-desktop/blob/3756a89076b169f075ca4ab75020f51c2ef00e79/packages/main/src/plugin/provider-registry.ts#L924)

**Comment by dgolovin** [comment]
I will close duplicate https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/16

**Comment by dgolovin** [comment]
@benoitf I think I saw some telemetry requested above already gathered for Create New form, is that correct?

**Comment by benoitf** [comment]
but you have generic data but here I think it's to have specific data

**Comment by dgolovin** [comment]
@slemeur  @benoitf I created new issue for sending telemetry when extension installed and removed https://github.com/containers/podman-desktop/issues/3018. 

Everything else should be reported from extension.

**Comment by dgolovin** [comment]
@slemeur from list below extension can intercept only (2) and (5) to send telemetry, because implementation for create and delete command comes from extension.
1 Click on "create New" from the resources page
2 Click on "create" in the Create a Developer Sandbox
3 Click on "Close" in the Create a Developer Sandbox
4 Click on "Log into Developer Sandbox" button
5 Click on delete the resource

Telemetry for other events ether can be sent from podman-desktop side. Podman-desktop can send telemetry itself or delegate it to extension in form of callbacks or notifications. 

@benoitf what way do you think we should take? I would say callbacks, because it this case we can have consistent telemetry event ids and that would, I think, make it easier to generate extension specific reports.
